# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# [Open Graph Protocol](https://ogp.me/)
og_enabled: true
og_image: /favicon.png
og:
  # customize og properties here which will replace the defaults

# show excerpt on post list
show_excerpt: true

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: false
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# choose from [auto, always]
rainbow_banner_shown: auto
# Pride Month by default
rainbow_banner_month: 6

# TOC - table of contents
toc: false
toc_max_depth: 2

# scroll reveal (https://scrollrevealjs.org/) - animating elements as they enter/leave the viewport
scroll_reveal: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Home
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Categories: /categories
    About Us: /about
    Official Site: https://www.bingyan.net
    # these will be automatically be an icon
    GitHub: https://github.com/BingyanStudio
    Search: /search

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    ä¸»é¡µ: /
    å½’æ¡£: /archives
    ä¸»é¢˜: /categories
    å…³äºæˆ‘ä»¬: /about
    æœç´¢: /search
    RSS: /atom.xml
  Links:
    # items
    å®˜ç½‘: https://bingyan.net
    æ¸¸æˆç»„å®˜ç½‘: https://bingyan.itch.io
    å¾®ä¿¡å…¬ä¼—å·:
    GitHub: https://github.com/BingyanStudio
    çŸ¥ä¹: https://www.zhihu.com/people/by_bingyan
  Contact Us:
    contact@bingyan.net: mailto:contact@bingyan.net

members:
  # Hamster:
  #   avatar: https://hamster5295.github.io/avatar.webp
  #   description: ğŸ¹ ä»“é¼ è¶…çº§å¯çˆ±ï¼
  #   homepage: https://hamster5295.github.io
  #   github: https://github.com/hamster5295
  # ligen131:
  #   avatar: https://ligen.life/img/119364574_p02.jpg
  #   description: Don't worry, be happy.
  #   homepage: https://ligen.life
  #   github: https://github.com/ligen131
  å¾…è¡¥å……:
    avatar: https://avatars.githubusercontent.com/u/86649490
    description: 
    homepage: https://just-plain.fun
    github: https://github.com/YiNNx
  # Capybara:
  #   avatar: https://avatars.githubusercontent.com/u/110143758?v=4
  #   description: Bara Bara Bara!
  #   homepage: 
  #   github: https://github.com/wangyinyuan
  # Chales Xu:
  #   avatar: https://avatars.githubusercontent.com/u/111160781?v=4
  #   description: ğŸŒŠğŸŒŠğŸŒŠ
  #   homepage: https://www.n2ptr.space/
  #   github: https://github.com/SHA-4096

# footer extra description
footer_extra_description: 2024 Â© Powered by Bingyan Studio & Hexo. All Rights Reserved.

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# search
# based on [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)
search: true
search_path: search.json
